name: Publish JSR

on:
  workflow_run:
    workflows:
      - "CI" # must match the CI workflow's `name:` exactly
    types:
      - completed
    branches:
      - main # Only run when CI completes on main branch

jobs:
  publish:
    runs-on: ubuntu-latest
    # Additional safety check: only run if CI succeeded
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          cache: true

      - name: Publish package
        run: deno publish
